// AUTO-GENERATED by scripts/fetch-api-testing-examples.mjs — do not hand-edit.
// Each example pairs one Playwright test() with its matching Postman
// request + Tests script, extracted verbatim from
// https://github.com/WRTHY/API-testing-sample/tree/master, refreshed 2026-09-03.
// To add/remove/retitle an example, edit src/content/apiTestingManifest.json
// and run `npm run fetch:api-testing`.

import type { ApiTestingExample } from './apiTesting'

export const apiTestingExamples: readonly ApiTestingExample[] = [
  {
    "id": "single-resource-positive",
    "tag": "Resources",
    "title": "Get single resource — positive case (existing id)",
    "description": "The happy path for reqres's actual \"single resource\" endpoint: fetch a resource that exists and confirm the full response — status, schema, and content — not just a status code. Toggle between the manual Postman check and its automated Playwright equivalent.",
    "playwright": {
      "filename": "tests/resources.spec.ts",
      "language": "typescript",
      "code": "import { test, expect } from \"@playwright/test\";\n\nconst endpointUnderTest = \"unknown\";\n\ntest(\"lookup with existing id - returns 200 with specified resource information\", async ({\n  request,\n}) => {\n  const start = Date.now();\n  const response = await request.get(`${endpointUnderTest}/2`);\n  const responseTime = Date.now() - start;\n\n  // validate status code\n  expect(response.status()).toBe(200);\n\n  const body = await response.json();\n  const entry = body.data;\n\n  // validate schema\n  expect(Object.keys(entry).sort()).toEqual(\n    [\"id\", \"name\", \"year\", \"color\", \"pantone_value\"].sort(),\n  );\n\n  // validate that the correct information is being returned\n  expect(entry.name).toEqual(\"fuchsia rose\");\n  expect(entry.color).toEqual(\"#C74375\");\n\n  // validate response time\n  expect(responseTime).toBeLessThan(500);\n});\n"
    },
    "postman": {
      "filename": "postman/reqres-api-collection.json",
      "language": "javascript",
      "code": "// GET {{baseUrl}}/unknown/2\n\npm.test(\"Status code is 200\", function () {\n    pm.response.to.have.status(200)\n})\n\npm.test(\"Response includes proper schema\", function() {\n    const response = pm.response.json().data;\n    pm.expect(response).to.have.all.keys('id', 'name', 'year', 'color', 'pantone_value')\n})\n\npm.test(\"Color 2 is fuchsia rose\", function () {\n    const response = pm.response.json()\n    pm.expect(response.data.name).to.eql('fuchsia rose')\n    pm.expect(response.data.color).to.eql('#C74375')\n})\n\npm.test(\"Response is recieved within 500 ms\", function (){\n    pm.expect(pm.response.responseTime).to.be.below(500)\n})\n"
    }
  },
  {
    "id": "single-resource-negative",
    "tag": "Resources",
    "title": "Get single resource — negative case (nonexistent id)",
    "description": "The other half of the pair: request a resource id that doesn't exist and confirm the API fails correctly with a 404 and an empty body, not a 500 or a silently-wrong 200.",
    "playwright": {
      "filename": "tests/resources.spec.ts",
      "language": "typescript",
      "code": "import { test, expect } from \"@playwright/test\";\n\nconst endpointUnderTest = \"unknown\";\n\ntest(\"lookup with incorrect id - returns 404 with an empty body\", async ({\n  request,\n}) => {\n  const start = Date.now();\n  const response = await request.get(`${endpointUnderTest}/23`);\n  const responseTime = Date.now() - start;\n\n  // validate status code\n  expect(response.status()).toBe(404);\n\n  const body = await response.json();\n\n  // validate schema\n  expect(body).toEqual({});\n\n  // validate response time\n  expect(responseTime).toBeLessThan(500);\n});\n"
    },
    "postman": {
      "filename": "postman/reqres-api-collection.json",
      "language": "javascript",
      "code": "// GET {{baseUrl}}/unknown/23\n\npm.test(\"Status code is 404\", function () {\n    pm.response.to.have.status(404)\n})\n\npm.test(\"Response body is empty\", function () {\n    pm.expect(pm.response.json()).to.eql({})\n})\n\npm.test(\"Response is received within 500 ms\", function (){\n    pm.expect(pm.response.responseTime).to.be.below(500)\n})\n"
    }
  }
] as const
