// AUTO-GENERATED by scripts/fetch-api-testing-examples.mjs - do not hand-edit.
// Each example is one test(), extracted verbatim from
// https://github.com/WRTHY/API-testing-sample/tree/master, refreshed 2026-09-02.
// To add/remove/retitle an example, edit src/content/apiTestingManifest.json
// and run `npm run fetch:api-testing`.

import type { ApiTestingExample } from './apiTesting'

export const apiTestingExamples: readonly ApiTestingExample[] = [
  {
    "id": "auth",
    "tag": "Auth",
    "title": "Login - negative case (missing password)",
    "description": "One test from the Auth suite: confirms the API fails loudly and correctly on a malformed request, without locking the assertion to reqres.in's exact error copy.",
    "filename": "tests/auth.spec.ts",
    "language": "typescript",
    "code": "import { test, expect } from '@playwright/test';\n\ntest('login - missing password - returns 400 with error message (negative case)', async ({\n  request,\n}) => {\n  const response = await request.post('/login', {\n    data: { email: 'peter@klaven' },\n  });\n\n  expect(response.status()).toBe(400);\n  const body = await response.json();\n  expect(body).toHaveProperty('error');\n  expect(typeof body.error).toBe('string');\n  expect(body.error.length).toBeGreaterThan(0);\n\n  // Deliberately NOT asserting the exact error string here. reqres owns\n  // that copy, not us - asserting on presence + shape instead of exact\n  // text is what keeps this test from breaking the next time they tweak\n  // a message. This is a real design decision, and a good one to be able\n  // to explain: what should a test lock down vs. leave loose?\n});\n"
  },
  {
    "id": "users",
    "tag": "Users",
    "title": "List users - boundary case (page far beyond total)",
    "description": "One test from the Users suite: what the API does when asked for a page number past the last real one - an easy case to skip by hand and a good automation candidate.",
    "filename": "tests/users.spec.ts",
    "language": "typescript",
    "code": "import { test, expect } from '@playwright/test';\n\ntest('list users - page far beyond total_pages - returns 200 with empty data (boundary case)', async ({\n  request,\n}) => {\n  // Boundary/edge testing: what happens past the last valid page?\n  // This is the kind of case that's easy to skip manually and easy to\n  // forget to re-check by hand after every change - a good automation\n  // candidate.\n  const response = await request.get('/users?page=9999');\n\n  expect(response.status()).toBe(200);\n  const body = await response.json();\n  expect(body.data).toEqual([]);\n});\n"
  }
] as const
