name: Run Testing on Push
run-name: ${{ github.actor }} triggered a test run with ${{ github.event_name }}
on: 
  push:
    - master
  pull_request:
    - opened
jobs:
  Run-Component-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test:unit
        
      - run: echo "Confirmation that the component testing has run"

